server:
  port: 8080


#  springdoc:
#    swagger-ui:
#      path: /swagger-ui.html
#      tags-sorter: alpha
#      operations-sorter: alpha
#    api-docs:
#      path: /v3/api-docs
#    group-configs:
#      - group: 'default'
#        paths-to-match: '/**'
#        packages-to-scan: controller
#  knife4j:
#    enable: true
#    setting:
#      language: zh_cn
#    basic:
#      enable: true
#      username: ewing
#      password: ewing

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan:
        # 配置接口文档扫描包路径，每个服务的路径不同，下面是系统服务(youlai-system)的包路径
        - com.ewing.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyroom?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: studyroom
    password: studyroom
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
