#
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: controller
#knife4j:
#  enable: true
#  setting:
#    language: zh_cn
#  basic:
#    enable: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'room'
      paths-to-match: '/**'
      packages-to-scan:
        # 配置接口文档扫描包路径，每个服务的路径不同，下面是系统服务(youlai-system)的包路径
        - com.ewing.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/studyroom?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: studyroom
    password: studyroom
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 6379
      password: 200103

xxl:
  job:
    admin:
      address: http://localhost:9998/xxl-job-admin  # 确保使用 singular 'address'
    executor:
      appname: room-executor
      address:                           # 可留空，XXL-JOB 会自动获取
      ip: 127.0.0.1                      # 可留空，XXL-JOB 会自动获取
      port: 9997                          # 可留空，XXL-JOB 会自动分配
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
      accessToken: default_token